project_id = "paqlcflzhjpgvlgcfrfj"

[functions.fetch-google-sheet]
verify_jwt = false

[functions.fetch-testimonials-sheet]
verify_jwt = false

[functions.fetch-media-sheet]
verify_jwt = false

[functions.fetch-content-sheet]
verify_jwt = false
